/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TestGroceryCounter {

  GroceryCounter groceryCounter;

  @Test
  public void testInitialValue() {
        GroceryCounter counter = new GroceryCounter();
        assertEquals("$0.00", counter.total());
        assertEquals(0, counter.overflows());
    }

  @Test
    public void testTensOnesHundreths() {
        GroceryCounter counter = new GroceryCounter();

        counter.tens();
        counter.tens();
        counter.hundreths();

        assertEquals("$20.01", counter.total());
        assertEquals(0, counter.overflows());
    }

    @Test
    public void testOnesButtonLoop() {
        GroceryCounter counter = new GroceryCounter();

        for (int i = 0; i < 35; i++) {
            counter.ones();
        }

        assertEquals("$35.00", counter.total());
        assertEquals(0, counter.overflows());
    }

    @Test
    public void testOverflow() {
        GroceryCounter counter = new GroceryCounter();

        counter.ones(); 
        for (int i = 0; i < 9999; i++) {
            counter.hundreths(); 
        }

        assertEquals(1, counter.overflows());
        assertEquals("$1.00", counter.total());
    }

    @Test
    public void testClear() {
        GroceryCounter counter = new GroceryCounter();

        counter.tens();
        counter.tens();
        counter.hundreths();
        counter.clear();

        assertEquals("$0.00", counter.total());
        assertEquals(0, counter.overflows());
    }

}
